### ISSUE TITLE
unable to connect gui

### ISSUE THREAD

**Issue by psoba** [bwya77/o365_Admin_Center#4]
i have met all the prerequisites but still get the error of login, and installs and policy all has been installe d and set and i still get the error.

i  am using windows 8.1

**Comment by bwya77** [comment]
Run each line below in regular powershell to figure out where its failing. Let me know!

 $global:o365creds = (Get-Credential -Message "O365 Credentials")

Connect-MsolService -Credential $global:o365creds

$exchangeSession = New-PSSession -Name MainAccount -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $global:o365creds -Authentication Basic -AllowRedirection

 Import-PSSession $exchangeSession -AllowClobber

**Comment by psoba** [comment]
we have office 365 but the only module we do not use is exchange online so i am guessing this is why the GUI is not working

**Comment by bwya77** [comment]
Looks like it since the connection URI is https://outlook.office365.com/powershell-liveid/ -Credential $global:o365creds -Authentication Basic -AllowRedirection

**Comment by psoba** [comment]
thanks for the quick update will give it a try

**Comment by psoba** [comment]
thanks for all your help will try again when we have exchange online which will be soon :-)

**Comment by bwya77** [comment]
no problem! let me know if you have any other issues

**Comment by psoba** [comment]
thanks will do, great tool will be really useful
