### ISSUE TITLE
Website Offline

### ISSUE THREAD

**Issue by matstocks** [bwya77/o365_Admin_Center#6]
Your website shows a database error when browsing to it.

**Comment by bw3p-git** [comment]
I'm able to get to it from multiple devices on different networks are you still having issues

Sent from Ninehttp://www.9folders.com/

**Comment by bwya77** [comment]
I am also able to get to it

**Comment by matstocks** [comment]
Seems to be working now. Must have been a gglittch.

Regards,
Mat

pacIT Technical Services Ltd
Mat Stocks
Managing Director, pacIT Technical Services Ltd
T: +44(0)1489 668866 | M: 07480640298
E: mat@pacit-tech.co.uk | W: www.pacit-tech.co.uk
A: 57 Dumas Drive, Whiteley, Hampshire, PO15 7LU
Pacit Technical Services Ltd is a company registered in England and Wales under number 9249289. The company's registered office is Rosewood, Brook Lane, Botley, Hampshire, SO30 2ER, United Kingdom.The information transmitted, including
attachments, is intended only for the person(s) or entity to which it is
addressed and may contain confidential and/or privileged material. Any review,
retransmission, dissemination or other use of, or taking of any action in
reliance upon this information by persons or entities other than the intended
recipient is prohibited. If you received this in error please contact the
sender and destroy any copies of this information.
