### ISSUE TITLE
Can't contact author to purchase

### ISSUE THREAD

**Issue by morrie-morrie** [bwya77/o365_Admin_Center#9]
Hi all,

Struggling to purchase this software. It appears to be updating through here, but the proper website's purchasing says it's out of stock.. Anyone now what is going on with this..

I really like it and would save us heaps of time..

Andrew Morison.

**Comment by jasondrhodes71** [comment]
Yes same here, the latest version is the one I have as per below, and it does not work on 1803.

                                
O365 Admin Center 


Version: 4.1.2.0
Version Release Date: 4/27/2017
Website: https://www.o365admin.center
FAQ: https://www.o365admin.center/FAQ

**Comment by morrie-morrie** [comment]
Hey Jason,

Thanks for letting me know..  Hopefully the author can respond and let us know what’s happening..
Maybe a dead project? Shame.. Seems like a great piece of software.

Regards

Andrew Morison

IT Group Manager
Email Address: andrew@techno.com.au<mailto:andrew@techno.com.au>
Helpdesk Support:  1300 130 412
Head Office: +61 3 9371 6300
Website: www.techno.com.au<http://www.techno.com.au/>

[cid:image002.jpg@01CEBAB2.F7D79990]

Disclaimer: The information contained in this e-mail is confidential: it is only intended for the recipient(s) named above.  If you have received this e-mail in error, please notify the sender so that arrangements can be made for its retrieval or destruction. Privacy: We will neither trade, rent nor sell your contact details to any party for any reason.
[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:_2_058F5CE8058F5A94007DE2CBCA2576C7]  Please consider the environment before printing this e-mail notice.

**Comment by Chockster** [comment]
I've had no contact after sending a mail in May to request a redownload of my purchased version, as the auto update mechanism doesn't currently work for us (although that may be firewall related). Not holding out much hope.

**Comment by bwya77** [comment]
I've opened sourced the project to the community, you can download it all and compile it. Let me know if you need an exe/msi file and I can compile and send it over.

**Comment by mikerharvey2004** [comment]
Hi,

Very interested in taking a look at this project. But my background is more in Powershell than general development. So can I confirm that I can view / edit the project by using Visual studio? I assume I would need something like Powershell Pro Tools for Visual Studio 2017 to be able to view / edit the  forms?

Thanks
Mike

**Comment by morrie-morrie** [comment]
Looks like PowerShell Studio

https://www.sapien.com/software/powershell_studio


Regards

Andrew Morison

IT Group Manager
Email Address: andrew@techno.com.au<mailto:andrew@techno.com.au>
Helpdesk Support:  1300 130 412
Head Office: +61 3 9371 6300
Website: www.techno.com.au<http://www.techno.com.au/>

[cid:image002.jpg@01CEBAB2.F7D79990]

Disclaimer: The information contained in this e-mail is confidential: it is only intended for the recipient(s) named above.  If you have received this e-mail in error, please notify the sender so that arrangements can be made for its retrieval or destruction. Privacy : We will neither trade, rent nor sell your contact details to any party for any reason.
[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:_2_058F5CE8058F5A94007DE2CBCA2576C7]  Please consider the environment before printing this e-mail notice.

**Comment by mhunter509** [comment]
Could you post a link to download a compiled exe? I don't have Powershell Studio and it looks like the code might be for an older version of the software.

**Comment by bwya77** [comment]
Hi everyone you can find the compiled EXE and MSI here: https://github.com/bwya77/O365-Admin-Center/tree/master/O365%20Admin%20Center%20Compiled
